### ISSUE TITLE
Table creation from the program

### ISSUE THREAD

**Issue by ogi-ts-shimizu** [aistairc/pygeoapi-mf-api#4]
**Is your feature request related to a problem? Please describe.**
The sql files were stored in the following folder
- tests/data
These SQL files were being called in the main.yml workflow file of GitHub Actions:

- .gitHub/workflows/main.yml

![main yml](https://github.com/user-attachments/assets/5ab2250f-996d-423a-abd8-8bb339dda022)

Since these SQL files were only called within main.yml, I'm wondering if mf-api requires a similar process.
Currently, it's unclear how to auto create tables from program, so the documentation instructs users to create them by executing commands.
![table create](https://github.com/user-attachments/assets/9c9c23bd-3c14-4909-a118-ddfc26c2575a)

You mentioned that I should refer to “records” in the web conference,
I did not know specifically which part of the process.

**Describe alternatives you've considered**
Could you please provide instructions on the process and necessary modifications for the relevant parts? I will then implement the changes accordingly.

**Comment by TaehoonK** [comment]
Looking at the code in pygeoapi, there are two ways to create a table. 
1) by specifying it in config.yaml
2) Using a backup file in the DB (but only for testing)

However, I believe that method 1) only works when creating a single table. 
We need to create multiple tables in our case, so we will have to use the SQL file like 2) for now. 

I've asked Tom, the project's maintainer, about this. 
If I get an answer, I'll share it with you.

**Comment by TaehoonK** [comment]
I've got an email from Tom and got confirmation of using the SQL file. 
The current system (#1) is implemented with SQL files.
